# -*- coding: utf-8 -*-
"""zipfinder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QHf0rp8vFQ4x3SYZzQ7ykaAMGIJxcxdA
"""

# Commented out IPython magic to ensure Python compatibility.
# Loading Data Processing Packages
import numpy as np # linear algebra
import pandas as pd # data frame manipulation
from numpy import nan
from numpy import isnan
from pandas import read_csv


zip = pd.read_csv("./plantrec - Sheet3.csv") #loading training data
testsubmission = pd.read_csv("./querytodo.csv") #loading test datat
del zip["state"]
zip.head()

def search_zip(zipcode): 
  zipcode = int(zipcode)
  usr = zip.loc[zip['zip_code'] == zipcode]
  city = usr["city"]
  city = str(city)
  usrlist = usr.values.tolist()
  city = usrlist[0][2]
  zone = usrlist[0][1]
  zipout = ('Based on your Zip Code, we found that you live in',city, ' and your USDA Plant Hardiness Zone is:', zone )
  return city, zone